### ISSUE TITLE
[Feature Request] Android/Google/Apple TV App Frontend

### ISSUE THREAD

**Issue by EffakT** [bhj/react-redux-starter-kit#59] opened 2023-04-18 21:06 UTC
Just want to create this as a feature request.

The idea is to have an app that can be installed on Android/Google/Apple TV. This app would only contain the front-end code, no server functionality. This would remove the requirement of using a browser on a TV (horrible experience), and make it a more native experience on the device.

To start with this could simply be a hybrid app, however in the future could be built native.

### Things to think about ###

- Do we need the whole front-end in the app, or could it simple be the login & player? E.G force control using the Remote Control? This would require a QR code in the player that links the remote device to the remote control.
- Is it best to use Native, or Hybrid apps for this?

**Comment by vinaykapadia** [comment] 2023-04-18 22:04
if any of those platforms have a web browser, could just use that. would be nice to have a native app though.

**Comment by vinaykapadia** [comment] 2023-04-18 22:04
nm, didn't see that you already mentioned the browser.

**Comment by bhj** [comment] 2023-04-20 02:21
Just to be clear, there's no requirement to use a TV's browser (treating them as dumb displays over wireless or wires is often better) but the first thing I'd ask is still: what can we do to improve the experience on TV browsers?

As far as the player, it's built on web tech by design. There's nothing preventing it from being wrapped in a webview, but the plan is to continue targeting browsers rather than, say, the current app store duopoly. Doesn't mean others can't try to port it to non-open platforms (and I like my Apple TV) but I'm not keen on directing energy toward them currently.

**Comment by EffakT** [comment] 2023-04-20 05:14
The main drawback for me using a TV browser is that say you have it setup on a TV in a shared space. All of these users that could use the TV can access KaraokeEternal via the TV.

In Google TV, the best browser available is called TV Bro, however from what I can tell, there is no way of adding a homepage shortcut to go straight to the KaraokeEternal app. This means the user needs to know the URL to access the app.

Additionally, the browser uses the arrow buttons on the remote control to move a cursor around the screen, instead a more accessible way would be to use the arrow buttons on the remote to select different elements. I understand this is more of a browser-end thing, however would be solved by using a native app.

**Comment by bhj** [comment] 2023-05-12 19:24
I'm all for improving the experience on TV browsers, so let's create a new issue for any tangible changes there. Going ahead and closing this one since there aren't currently plans to target "non-browser" platforms.

**Closed as not planned by bhj** 2023-05-12 19:24 UTC
